name: Xin file ban quyen tu may chu 🔑
on:
  push:
    branches:
      - main
jobs:
  request-alf:
    runs-on: ubuntu-latest
    steps:
      - name: Yeu cau file ALF
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2 # PHIÊN BẢN V2
        with:
          unityVersion: '6000.3.22f1'
      - name: Tai file ALF ve
        uses: actions/upload-artifact@v4
        with:
          name: File-ALF-Cua-May-Chu
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}